### PR TITLE
Issue #22: Created backend project structure; imported dependencies; …

### LINKED ISSUE #22: Back-end setup
Setup directory structure, README and dependencies

### PR DESCRIPTION
**Pull request by NeaGogu**
…wrote README with structure description and motivation

### CODE REVIEW

**Comment by NeaGogu** [comment]
Fixes #22

**Comment by PhilipWaldman** [comment]
The code runs for me.
I would just recommend running auto-format (ctrl-shift-L in Goland, probably something else in VSCode). That way everyone's formatting (indentations, etc) will be more consistent.

**Review by Lucasmeteenc — CHANGES_REQUESTED** [review]
Add how to run to program in README

**Review by VictorVader — DISMISSED** [review]
Please also add how to setup github with goland in the readme file

**Comment by NeaGogu** [comment]
> Please also add how to setup github with goland in the readme file

What do you mean :laughing:

**Review by Lucasmeteenc — APPROVED** [review]
Nice this is good

**Review by Lucasmeteenc — APPROVED** [review]
good

**Review by Patricijia — APPROVED** [review]

**Pull request merged**
